# Generated by Django 2.1.3 on 2019-05-17 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='')),
                ('date', models.DateField(default='2019-05-19')),
                ('isApproved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=1)),
                ('payAmt', models.DecimalField(decimal_places=2, default=-1, max_digits=10)),
                ('isPaid', models.BooleanField(default=False)),
                ('paymentFailed', models.BooleanField(default=False)),
                ('requestingVerification', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usrname', models.CharField(blank=True, default='', max_length=100)),
                ('isParent', models.BooleanField(default=False)),
                ('displayName', models.CharField(blank=True, default='', max_length=100)),
                ('childName', models.CharField(blank=True, default='', max_length=100)),
                ('money', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('phoneNumber', models.IntegerField(blank=True, default=-1)),
                ('teacher', models.CharField(blank=True, default='', max_length=100)),
                ('comments', models.TextField(default='none')),
                ('parentsFeedback', models.TextField(default='none')),
                ('twoFaKey', models.CharField(blank=True, default='', max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
