# Generated by Django 2.2 on 2019-05-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='IsPaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='Money',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='student',
            name='ParentName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='StudentName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
