# Generated by Django 2.2 on 2019-05-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190515_0139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='ParentName',
            new_name='ChildName',
        ),
        migrations.AddField(
            model_name='student',
            name='IsParent',
            field=models.BooleanField(default=False),
        ),
    ]
