# Generated by Django 2.2 on 2019-05-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190515_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='ChildName',
            new_name='childName',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='StudentName',
            new_name='displayName',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='IsPaid',
            new_name='isPaid',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='IsParent',
            new_name='isParent',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Money',
            new_name='money',
        ),
        migrations.AddField(
            model_name='student',
            name='usrname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
