# Generated by Django 2.2 on 2019-05-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190515_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phoneNumber',
            field=models.IntegerField(default=-1),
        ),
    ]
