# Generated by Django 2.2 on 2019-05-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_student_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='comments',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='student',
            name='parentsFeedback',
            field=models.TextField(default='none'),
        ),
    ]
