# Generated by Django 2.2 on 2019-05-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190515_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.CharField(default='', max_length=100),
        ),
    ]
