# Generated by Django 2.2 on 2019-05-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_student_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='none')),
                ('isApproved', models.BooleanField(default=False)),
            ],
        ),
    ]
