# Generated by Django 2.2 on 2019-05-15 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
