# Generated by Django 2.2 on 2019-05-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190515_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default='2019-05-19'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
