# Generated by Django 2.2 on 2019-05-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20190515_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='childName',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='displayName',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='money',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='phoneNumber',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='student',
            name='teacher',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='usrname',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
