# Generated by Django 2.2 on 2019-05-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20190516_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='payAmt',
            field=models.DecimalField(decimal_places=2, default=-1.0, max_digits=10),
        ),
    ]
