# Generated by Django 2.2 on 2019-05-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_student_payamt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payAmt', models.DecimalField(decimal_places=2, default=-1, max_digits=10)),
                ('isPaid', models.BooleanField(default=False)),
                ('requestingVerification', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='isPaid',
        ),
        migrations.RemoveField(
            model_name='student',
            name='payAmt',
        ),
    ]
