# Generated by Django 2.2 on 2019-05-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20190516_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='index',
            field=models.IntegerField(default=1),
        ),
    ]
