# Generated by Django 2.2 on 2019-05-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_payment_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paymentFailed',
            field=models.BooleanField(default=False),
        ),
    ]
