# Generated by Django 2.2 on 2019-05-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_payment_paymentfailed'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='isMakingTransaction',
            field=models.BooleanField(default=False),
        ),
    ]
