# Generated by Django 2.2 on 2019-05-16 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_student_ismakingtransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='isMakingTransaction',
        ),
    ]
